import type { Recipe } from './types';
import { SITE_URL } from '../site';

/** Branded placeholder images generated by scripts/generate-recipe-images.py */
export function getRecipeImagePath(recipe: Pick<Recipe, 'slug'>): string {
  return `/recipes/images/${recipe.slug}.jpg`;
}

export function getRecipeImageUrl(recipe: Pick<Recipe, 'slug'>): string {
  return `${SITE_URL}${getRecipeImagePath(recipe)}`;
}
