import type { Recipe } from './types';

/** Low carb & keto recipes with estimated net carbs per serving. */
export const RECIPES: Recipe[] = [
  {
    slug: 'scrambled-eggs-spinach',
    title: 'Scrambled Eggs with Spinach',
    description:
      'Quick high-protein breakfast with minimal net carbs. Blood-sugar-friendly start for keto and insulin resistance meal plans.',
    category: 'breakfast',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 2,
    proteinPerServing: 18,
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 8,
    ingredients: [
      '2 large eggs',
      '1 cup fresh spinach',
      '1 tbsp butter or olive oil',
      'Salt and pepper to taste',
      'Optional: 1 tbsp shredded cheddar',
    ],
    steps: [
      'Warm butter in a non-stick pan over medium heat.',
      'Add spinach; cook until wilted, about 2 minutes.',
      'Beat eggs with salt and pepper; pour into the pan.',
      'Stir gently until set. Add cheese if using. Serve immediately.',
    ],
    tips: 'Pair with black coffee or unsweetened tea. Skip cheese to keep net carbs lowest.',
    relatedGuideSlugs: ['best-first-meal-after-fasting', 'how-to-break-a-24-hour-fast'],
  },
  {
    slug: 'chicken-salad-lettuce-cups',
    title: 'Chicken Salad Lettuce Cups',
    description:
      'Creamy chicken salad served in crisp lettuce wraps — low carb, high protein, no bread required.',
    category: 'lunch',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 3,
    proteinPerServing: 28,
    servings: 2,
    prepMinutes: 15,
    cookMinutes: 0,
    ingredients: [
      '2 cups cooked chicken, shredded',
      '3 tbsp mayonnaise',
      '1 tbsp Dijon mustard',
      '2 celery stalks, diced',
      '2 tbsp red onion, finely diced',
      '1 head butter lettuce or romaine leaves',
      'Salt, pepper, and fresh dill (optional)',
    ],
    steps: [
      'Mix chicken, mayo, mustard, celery, and onion in a bowl.',
      'Season with salt, pepper, and dill.',
      'Spoon mixture into lettuce leaves and serve.',
    ],
    tips: 'Use rotisserie chicken for speed. Check mayo labels — some brands add sugar.',
    relatedGuideSlugs: ['best-first-meal-after-fasting', 'how-to-break-a-24-hour-fast'],
  },
  {
    slug: 'baked-salmon-broccoli',
    title: 'Baked Salmon with Broccoli',
    description:
      'Simple sheet-pan style dinner rich in omega-3s and protein with about 6g net carbs per plate.',
    category: 'dinner',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 6,
    proteinPerServing: 34,
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 18,
    ingredients: [
      '2 salmon fillets (6 oz each)',
      '2 cups broccoli florets',
      '2 tbsp olive oil',
      '1 lemon, sliced',
      '2 garlic cloves, minced',
      'Salt, pepper, and dried herbs',
    ],
    steps: [
      'Preheat oven to 400°F (200°C).',
      'Toss broccoli with 1 tbsp oil, salt, and pepper on a baking sheet.',
      'Rub salmon with remaining oil, garlic, salt, and pepper. Top with lemon.',
      'Bake 15–18 minutes until salmon flakes and broccoli is tender.',
    ],
    tips: 'Wild-caught salmon is optional. Keep broccoli portions modest for strict keto days.',
    relatedGuideSlugs: ['fatty-liver-low-carb', 'net-carbs-for-insulin-resistance'],
  },
  {
    slug: 'cauliflower-rice-stir-fry',
    title: 'Cauliflower Rice Stir-Fry',
    description:
      'Low-carb stir-fry using riced cauliflower instead of grains — fills the plate without spiking carbs.',
    category: 'dinner',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 8,
    proteinPerServing: 22,
    servings: 3,
    prepMinutes: 15,
    cookMinutes: 12,
    ingredients: [
      '1 lb ground chicken or turkey',
      '4 cups riced cauliflower (fresh or frozen)',
      '2 tbsp coconut aminos or low-sodium soy sauce',
      '1 tbsp sesame oil',
      '1 cup mixed bell peppers, sliced',
      '2 green onions, chopped',
      '1 tsp ginger, minced',
      '2 garlic cloves, minced',
    ],
    steps: [
      'Brown meat in a large skillet; drain excess fat if needed.',
      'Add ginger, garlic, and peppers; cook 3 minutes.',
      'Stir in cauliflower rice; cook until heated through and slightly dry.',
      'Add coconut aminos and green onions. Toss and serve.',
    ],
    tips: 'Frozen cauli rice works — pat dry if very wet. Check sauce carbs on the label.',
  },
  {
    slug: 'greek-yogurt-berries',
    title: 'Greek Yogurt with Berries',
    description:
      'Higher-protein snack with controlled berries — fits moderate low carb more than strict keto.',
    category: 'snack',
    fitsPlans: ['low_carb_ir', 'moderate_low_carb'],
    netCarbsPerServing: 10,
    proteinPerServing: 15,
    servings: 1,
    prepMinutes: 3,
    cookMinutes: 0,
    ingredients: [
      '3/4 cup plain Greek yogurt (full-fat, unsweetened)',
      '1/4 cup raspberries or blackberries',
      '1 tbsp chopped walnuts (optional)',
      'Pinch of cinnamon',
    ],
    steps: [
      'Add yogurt to a bowl.',
      'Top with berries, nuts, and cinnamon.',
      'Serve cold.',
    ],
    tips: 'Strict keto? Use fewer berries or swap for a few sliced strawberries. Always check yogurt labels for added sugar.',
  },
  {
    slug: 'taco-bowl-no-tortilla',
    title: 'Taco Bowl (No Tortilla)',
    description:
      'All the taco flavor in a bowl — seasoned beef, avocado, cheese, and salsa without the wrap.',
    category: 'dinner',
    fitsPlans: ['low_carb_ir'],
    netCarbsPerServing: 9,
    proteinPerServing: 26,
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 15,
    ingredients: [
      '1 lb ground beef',
      '2 tbsp taco seasoning (low-sugar or homemade)',
      '2 cups shredded lettuce',
      '1/2 cup salsa (no sugar added)',
      '1/2 avocado, sliced',
      '1/2 cup shredded cheese',
      '2 tbsp sour cream',
      'Lime wedges',
    ],
    steps: [
      'Brown beef; drain fat. Stir in taco seasoning and a splash of water; simmer 2 minutes.',
      'Divide lettuce between bowls.',
      'Top with beef, salsa, avocado, cheese, and sour cream.',
      'Squeeze lime over the top and serve.',
    ],
    tips: 'Make your own seasoning to avoid cornstarch and sugar in packets.',
  },
  {
    slug: 'egg-muffins',
    title: 'Low Carb Egg Muffins',
    description:
      'Make-ahead egg cups with cheese and veggies — grab-and-go breakfast for busy mornings.',
    category: 'breakfast',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 2,
    proteinPerServing: 12,
    servings: 6,
    prepMinutes: 10,
    cookMinutes: 22,
    ingredients: [
      '8 large eggs',
      '1/2 cup shredded cheddar',
      '1/2 cup diced bell pepper',
      '1/2 cup spinach, chopped',
      'Salt, pepper, and paprika',
      'Cooking spray or butter for muffin tin',
    ],
    steps: [
      'Preheat oven to 350°F (175°C). Grease a 12-cup muffin tin.',
      'Whisk eggs with salt, pepper, and paprika.',
      'Divide peppers, spinach, and cheese among cups.',
      'Pour egg mixture over fillings. Bake 20–22 minutes until set.',
      'Cool 5 minutes before removing. Store in fridge up to 4 days.',
    ],
    tips: 'One muffin ≈ one serving. Reheat in microwave 30–45 seconds.',
  },
  {
    slug: 'zucchini-noodles-meat-sauce',
    title: 'Zucchini Noodles with Meat Sauce',
    description:
      'Classic meat sauce over zoodles — comfort food with a fraction of the pasta carbs.',
    category: 'dinner',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 9,
    proteinPerServing: 24,
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 25,
    ingredients: [
      '1 lb ground beef or Italian sausage',
      '4 medium zucchini, spiralized',
      '1 cup marinara (no sugar added)',
      '2 garlic cloves, minced',
      '1 tbsp olive oil',
      '1/2 tsp Italian seasoning',
      'Parmesan for serving',
      'Salt and pepper',
    ],
    steps: [
      'Brown meat with garlic; drain if needed. Stir in marinara and seasoning; simmer 10 minutes.',
      'Sauté zoodles in olive oil 2–3 minutes — do not overcook or they get watery.',
      'Plate zoodles, top with sauce and parmesan.',
    ],
    tips: 'Salt zoodles lightly and pat dry if very wet. Read marinara labels — many brands hide sugar.',
  },
  {
    slug: 'cottage-cheese-cucumber',
    title: 'Cottage Cheese & Cucumber Bowl',
    description:
      'Light, protein-rich snack or mini-meal with crunch and almost no prep.',
    category: 'snack',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 5,
    proteinPerServing: 14,
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 0,
    ingredients: [
      '3/4 cup full-fat cottage cheese',
      '1/2 cucumber, sliced',
      '1 tbsp olive oil or everything bagel seasoning',
      'Black pepper and fresh dill',
    ],
    steps: [
      'Add cottage cheese to a bowl.',
      'Top with cucumber, seasoning, pepper, and dill.',
      'Drizzle olive oil if desired.',
    ],
    tips: 'Choose cottage cheese with no added sugars or starches in the ingredients list.',
  },
  {
    slug: 'sheet-pan-sausage-peppers',
    title: 'Sheet Pan Sausage & Peppers',
    description:
      'One-pan dinner with minimal cleanup — hearty, low carb, and easy to scale for meal prep.',
    category: 'dinner',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 7,
    proteinPerServing: 18,
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    ingredients: [
      '4 links smoked sausage (sugar-free), sliced',
      '2 bell peppers, sliced',
      '1 red onion, sliced',
      '2 tbsp olive oil',
      '1 tsp dried oregano',
      'Salt and pepper',
    ],
    steps: [
      'Preheat oven to 425°F (220°C).',
      'Toss sausage, peppers, and onion with oil and seasonings on a sheet pan.',
      'Spread in a single layer.',
      'Roast 25–30 minutes, turning once, until browned and tender.',
    ],
    tips: 'Check sausage labels — many contain dextrose or maltodextrin. Sugar-free kielbasa or andouille works well.',
  },
  {
    slug: 'avocado-egg-boats',
    title: 'Avocado Egg Boats',
    description:
      'Baked eggs in avocado halves — protein and healthy fats with about 3g net carbs. Ideal first meal after a short fast.',
    category: 'breakfast',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 3,
    proteinPerServing: 14,
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 15,
    ingredients: [
      '1 ripe avocado, halved and pitted',
      '2 large eggs',
      'Salt, pepper, and everything bagel seasoning',
      'Optional: crumbled bacon or hot sauce',
    ],
    steps: [
      'Preheat oven to 425°F (220°C). Scoop out a little extra avocado if needed so eggs fit.',
      'Place halves in a small baking dish so they stay upright.',
      'Crack one egg into each half. Season with salt and pepper.',
      'Bake 12–15 minutes until whites are set and yolks are to your liking.',
    ],
    tips: 'Break a 16-hour fast with one half plus water or bouillon first if you are sensitive to rich foods.',
    relatedGuideSlugs: ['how-to-break-a-24-hour-fast', 'best-first-meal-after-fasting'],
  },
  {
    slug: 'smoked-salmon-cream-cheese-roll-ups',
    title: 'Smoked Salmon Cream Cheese Roll-Ups',
    description:
      'No-cook breakfast or lunch with omega-3s and zero cooking — about 2g net carbs per roll-up.',
    category: 'breakfast',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 2,
    proteinPerServing: 16,
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 0,
    ingredients: [
      '4 oz smoked salmon',
      '4 tbsp cream cheese, softened',
      '1/2 cucumber, cut into sticks',
      'Fresh dill and capers (optional)',
      'Lemon wedge',
    ],
    steps: [
      'Spread cream cheese thinly over each salmon slice.',
      'Add dill and capers if using. Place a cucumber stick at one end.',
      'Roll up tightly. Slice in half if desired.',
      'Serve with lemon.',
    ],
    tips: 'Use full-fat cream cheese with no added sugar. Pairs well after intermittent fasting.',
    relatedGuideSlugs: ['best-first-meal-after-fasting'],
  },
  {
    slug: 'turkey-avocado-roll-ups',
    title: 'Turkey & Avocado Roll-Ups',
    description:
      'Deli turkey wrapped around avocado and cheese — portable lunch under 4g net carbs.',
    category: 'lunch',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 4,
    proteinPerServing: 22,
    servings: 2,
    prepMinutes: 8,
    cookMinutes: 0,
    ingredients: [
      '8 slices deli turkey (no sugar added)',
      '1/2 avocado, sliced',
      '4 slices provolone or Swiss',
      'Mustard or mayo',
      'Lettuce leaves (optional)',
    ],
    steps: [
      'Lay turkey slices flat. Spread a thin layer of mustard or mayo.',
      'Add cheese and avocado. Roll tightly.',
      'Secure with a toothpick if needed. Wrap in lettuce for extra crunch.',
    ],
    tips: 'Read deli meat labels — honey ham and glazed turkey add hidden carbs.',
  },
  {
    slug: 'tuna-salad-stuffed-peppers',
    title: 'Tuna Salad Stuffed Mini Peppers',
    description:
      'Crunchy lunch cups with canned tuna and mayo — high protein, minimal carbs.',
    category: 'lunch',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 4,
    proteinPerServing: 24,
    servings: 2,
    prepMinutes: 12,
    cookMinutes: 0,
    ingredients: [
      '2 cans tuna in water, drained',
      '3 tbsp mayonnaise',
      '1 celery stalk, diced',
      '2 tbsp red onion, minced',
      '4 mini bell peppers, halved',
      'Salt, pepper, and lemon juice',
    ],
    steps: [
      'Mix tuna, mayo, celery, onion, and lemon juice.',
      'Season with salt and pepper.',
      'Spoon into pepper halves and serve.',
    ],
    tips: 'Swap peppers for cucumber boats for even fewer carbs.',
  },
  {
    slug: 'steak-salad-arugula',
    title: 'Steak Salad with Arugula & Parmesan',
    description:
      'Satisfying dinner salad with sliced sirloin, peppery greens, and olive oil dressing.',
    category: 'dinner',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 5,
    proteinPerServing: 32,
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 12,
    ingredients: [
      '12 oz sirloin or strip steak',
      '4 cups arugula',
      '1/4 cup shaved parmesan',
      '2 tbsp olive oil',
      '1 tbsp red wine vinegar',
      'Salt and pepper',
    ],
    steps: [
      'Season steak; sear in a hot pan 3–4 minutes per side for medium. Rest 5 minutes, then slice.',
      'Toss arugula with oil, vinegar, salt, and pepper.',
      'Top with steak and parmesan.',
    ],
    tips: 'Let steak rest before slicing — juices stay in the meat.',
  },
  {
    slug: 'lemon-garlic-chicken-thighs',
    title: 'Lemon Garlic Chicken Thighs',
    description:
      'Crispy skin chicken thighs with a bright lemon pan sauce — family-friendly low carb dinner.',
    category: 'dinner',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 3,
    proteinPerServing: 28,
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 35,
    ingredients: [
      '4 bone-in chicken thighs',
      '2 tbsp olive oil',
      '4 garlic cloves, minced',
      '1 lemon, juiced and zested',
      '1/2 cup chicken broth',
      '2 tbsp butter',
      'Salt, pepper, and parsley',
    ],
    steps: [
      'Pat thighs dry; season with salt and pepper.',
      'Sear skin-side down in oil over medium-high heat until golden, 6–7 minutes. Flip; cook 5 minutes.',
      'Add garlic; cook 30 seconds. Add broth, lemon juice, and zest.',
      'Simmer covered 15–20 minutes until cooked through. Stir in butter and parsley.',
    ],
    tips: 'Serve with roasted broccoli or a simple side salad.',
  },
  {
    slug: 'pork-chops-green-beans',
    title: 'Pan-Seared Pork Chops with Green Beans',
    description:
      'Classic protein-and-vegetable plate with about 6g net carbs — easy weeknight dinner.',
    category: 'dinner',
    fitsPlans: ['low_carb_ir'],
    netCarbsPerServing: 6,
    proteinPerServing: 30,
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 20,
    ingredients: [
      '2 bone-in pork chops (8 oz each)',
      '2 cups green beans, trimmed',
      '2 tbsp olive oil',
      '2 tbsp butter',
      '2 garlic cloves, minced',
      'Salt and pepper',
    ],
    steps: [
      'Season chops. Sear in oil 4–5 minutes per side until 145°F internal. Rest.',
      'In same pan, sauté green beans with garlic and butter 6–8 minutes until tender-crisp.',
      'Season beans and serve with chops.',
    ],
    tips: 'Butter-basting the chops in the last minute adds flavor without carbs.',
  },
  {
    slug: 'shrimp-garlic-butter-zucchini',
    title: 'Garlic Butter Shrimp with Zucchini',
    description:
      'Fast 20-minute dinner — shrimp scampi style over sautéed zucchini instead of pasta.',
    category: 'dinner',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 5,
    proteinPerServing: 26,
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 12,
    ingredients: [
      '1 lb large shrimp, peeled and deveined',
      '2 medium zucchini, sliced into half-moons',
      '3 tbsp butter',
      '3 garlic cloves, minced',
      '2 tbsp fresh parsley',
      'Red pepper flakes, salt, and lemon',
    ],
    steps: [
      'Sauté zucchini in 1 tbsp butter until just tender; set aside.',
      'Melt remaining butter; add garlic and pepper flakes. Cook 30 seconds.',
      'Add shrimp; cook 2–3 minutes per side until pink.',
      'Return zucchini to pan; toss with parsley and lemon juice.',
    ],
    tips: 'Do not overcook shrimp — they tighten and get rubbery.',
  },
  {
    slug: 'hard-boiled-eggs-everything-seasoning',
    title: 'Hard-Boiled Eggs with Everything Seasoning',
    description:
      'Zero-prep snack or mini-meal — 1g net carbs per egg, perfect for keto and break-fast windows.',
    category: 'snack',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 1,
    proteinPerServing: 6,
    servings: 2,
    prepMinutes: 2,
    cookMinutes: 12,
    ingredients: [
      '4 large eggs',
      'Everything bagel seasoning',
      'Salt and pepper',
      'Optional: mayo for deviled-style filling',
    ],
    steps: [
      'Place eggs in a pot; cover with cold water by 1 inch.',
      'Bring to a boil; cover, remove from heat, and rest 10–12 minutes.',
      'Ice bath 5 minutes. Peel and halve.',
      'Sprinkle with everything seasoning, salt, and pepper.',
    ],
    tips: 'Batch cook a dozen on Sunday for grab-and-go snacks all week.',
    relatedGuideSlugs: ['best-first-meal-after-fasting'],
  },
  {
    slug: 'cheese-olive-nut-plate',
    title: 'Cheese, Olive & Nut Snack Plate',
    description:
      'Charcuterie-style snack for moderate low carb — no cooking, about 4g net carbs per serving.',
    category: 'snack',
    fitsPlans: ['strict_keto', 'low_carb_ir', 'moderate_low_carb'],
    netCarbsPerServing: 4,
    proteinPerServing: 12,
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 0,
    ingredients: [
      '3 oz cheddar or gouda, cubed',
      '1/4 cup green olives',
      '2 tbsp almonds or macadamias',
      '2 slices salami (sugar-free)',
      'Optional: cucumber rounds',
    ],
    steps: [
      'Arrange cheese, olives, nuts, and salami on a plate.',
      'Add cucumber if desired. Serve immediately or pack for travel.',
    ],
    tips: 'Pre-portion nuts — they are easy to overeat and carbs add up.',
  },
  {
    slug: 'break-fast-bone-broth-eggs',
    title: 'Break-Fast Bone Broth & Soft Eggs',
    description:
      'Gentle refeed after 16–24 hour fasts — warm broth first, then soft eggs for protein and fat.',
    category: 'breakfast',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 2,
    proteinPerServing: 14,
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 8,
    ingredients: [
      '1 cup bone broth or bouillon (Dr. Westman style)',
      '2 large eggs',
      '1 tsp butter',
      'Salt and pepper',
      'Optional: chopped chives',
    ],
    steps: [
      'Warm broth in a mug — sip slowly over 10 minutes before eating solids.',
      'Soft-scramble or poach eggs in butter over low heat.',
      'Season eggs; garnish with chives. Eat slowly.',
    ],
    tips: 'Dr. Mindy recommends protein, fat, and fiber when breaking fasts — add spinach if tolerated.',
    relatedGuideSlugs: ['how-to-break-a-24-hour-fast', 'best-first-meal-after-fasting', 'electrolytes-during-fasting'],
  },
  {
    slug: 'chia-pudding-coconut',
    title: 'Overnight Chia Pudding (Coconut)',
    description:
      'Make-ahead breakfast with fiber — about 8g net carbs; best for moderate low carb, not strict keto daily.',
    category: 'breakfast',
    fitsPlans: ['low_carb_ir', 'moderate_low_carb'],
    netCarbsPerServing: 8,
    proteinPerServing: 8,
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 0,
    ingredients: [
      '1/4 cup chia seeds',
      '1 cup unsweetened coconut milk',
      '1/2 tsp vanilla extract',
      'Pinch of salt',
      'Optional: 2 tbsp unsweetened shredded coconut',
      'Optional: few raspberries on top',
    ],
    steps: [
      'Whisk chia, coconut milk, vanilla, and salt in a jar.',
      'Refrigerate at least 4 hours or overnight, stirring once.',
      'Divide between bowls; top with coconut or berries if using.',
    ],
    tips: 'Chia fiber counts toward net carbs on labels — this is moderate carb, not strict keto.',
  },
  {
    slug: 'cobb-salad-jar',
    title: 'Cobb Salad in a Jar',
    description:
      'Layered lunch prep with chicken, bacon, egg, and blue cheese — about 7g net carbs per jar.',
    category: 'lunch',
    fitsPlans: ['low_carb_ir'],
    netCarbsPerServing: 7,
    proteinPerServing: 30,
    servings: 2,
    prepMinutes: 20,
    cookMinutes: 0,
    ingredients: [
      '2 cups cooked chicken, diced',
      '4 cups romaine, chopped',
      '2 hard-boiled eggs, quartered',
      '2 slices cooked bacon, crumbled',
      '1/4 cup blue cheese crumbles',
      '1/2 cup cherry tomatoes, halved',
      '3 tbsp ranch dressing (no sugar)',
    ],
    steps: [
      'Layer dressing at the bottom of two large jars.',
      'Add tomatoes, chicken, eggs, bacon, cheese, then lettuce on top.',
      'Refrigerate up to 3 days. Shake into a bowl when ready to eat.',
    ],
    tips: 'Keeping dressing on the bottom prevents soggy lettuce.',
  },
  {
    slug: 'shakshuka-spinach-feta',
    title: 'Shakshuka with Spinach & Feta',
    description:
      'One-skillet eggs in spiced tomato sauce with wilted spinach — about 5g net carbs, high protein, and a satisfying break-fast or weekend brunch.',
    category: 'breakfast',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 5,
    proteinPerServing: 20,
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 18,
    ingredients: [
      '4 large eggs',
      '1 cup crushed tomatoes (no sugar added)',
      '1 cup fresh spinach',
      '1/2 small onion, diced',
      '1 tbsp olive oil',
      '1 tsp cumin',
      '1/2 tsp paprika',
      '2 oz feta, crumbled',
      'Salt, pepper, and fresh parsley',
    ],
    steps: [
      'Sauté onion in olive oil over medium heat until soft, 4–5 minutes.',
      'Stir in cumin, paprika, tomatoes, salt, and pepper. Simmer 5 minutes.',
      'Add spinach; stir until wilted. Make four wells in the sauce.',
      'Crack an egg into each well. Cover and cook until whites set, 6–8 minutes.',
      'Top with feta and parsley. Serve from the skillet.',
    ],
    tips: 'Check tomato labels — some brands add sugar. Pair with black coffee, not juice, after a fast.',
    relatedGuideSlugs: ['best-first-meal-after-fasting', 'getting-started-keto-low-carb', 'how-to-break-a-24-hour-fast'],
  },
  {
    slug: 'lettuce-wrap-burger-bowl',
    title: 'Lettuce Wrap Burger Bowl',
    description:
      'Deconstructed burger with seasoned beef, cheese, pickles, and sauce over greens — about 4g net carbs, ideal for insulin resistance lunches.',
    category: 'lunch',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 4,
    proteinPerServing: 28,
    servings: 2,
    prepMinutes: 12,
    cookMinutes: 10,
    ingredients: [
      '12 oz ground beef (80/20 or leaner)',
      '4 cups romaine or butter lettuce, chopped',
      '1/2 cup cherry tomatoes, halved',
      '1/4 cup dill pickles, diced',
      '2 oz cheddar, shredded',
      '2 tbsp mayonnaise',
      '1 tbsp sugar-free ketchup or mustard',
      '1 tsp Worcestershire sauce (check carbs)',
      'Salt, pepper, and onion powder',
    ],
    steps: [
      'Brown beef in a skillet over medium-high heat, breaking it up. Season with salt, pepper, and onion powder.',
      'Drain excess fat if needed. Stir in Worcestershire; remove from heat.',
      'Divide lettuce between bowls. Top with warm beef, tomatoes, pickles, and cheese.',
      'Mix mayo and ketchup/mustard; drizzle over bowls and toss lightly.',
    ],
    tips: 'Use our net carb calculator on condiments — “sugar-free” labels still vary by brand.',
    relatedGuideSlugs: ['net-carbs-for-insulin-resistance', 'how-to-read-nutrition-labels-net-carbs', 'getting-started-keto-low-carb'],
  },
  {
    slug: 'ginger-chicken-bone-broth-soup',
    title: 'Ginger Chicken Bone Broth Soup',
    description:
      'Light refeed soup with collagen-rich broth, shredded chicken, and ginger — about 3g net carbs. Dr. Westman–style assisted fasting support.',
    category: 'lunch',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 3,
    proteinPerServing: 18,
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 15,
    ingredients: [
      '4 cups chicken bone broth (low sodium)',
      '1 cup cooked chicken, shredded',
      '1 tbsp fresh ginger, grated',
      '2 green onions, sliced',
      '1 cup bok choy or spinach',
      '1 tbsp coconut aminos or tamari',
      '1 tsp sesame oil',
      'Salt, white pepper, and lime wedge',
    ],
    steps: [
      'Bring broth to a gentle simmer in a pot. Add ginger and chicken.',
      'Stir in bok choy; cook 2 minutes until just tender.',
      'Remove from heat. Add coconut aminos, sesame oil, and green onions.',
      'Ladle into mugs or bowls. Finish with lime and white pepper.',
    ],
    tips: 'Sip slowly when breaking extended fasts — broth first, then solids. See our electrolytes guide for sodium needs.',
    relatedGuideSlugs: ['electrolytes-during-fasting', 'how-to-break-a-24-hour-fast', 'water-fast-vs-assisted-fast', 'best-first-meal-after-fasting'],
  },
  {
    slug: 'salmon-avocado-poke-bowl',
    title: 'Salmon Avocado Poke Bowl',
    description:
      'Omega-3-rich salmon with avocado and cucumber — about 7g net carbs. A PCOS- and fatty-liver-friendly dinner with steady protein and healthy fats.',
    category: 'dinner',
    fitsPlans: ['strict_keto', 'low_carb_ir', 'moderate_low_carb'],
    netCarbsPerServing: 7,
    proteinPerServing: 32,
    servings: 2,
    prepMinutes: 15,
    cookMinutes: 0,
    ingredients: [
      '12 oz sushi-grade or previously frozen salmon, cubed',
      '1 avocado, diced',
      '1 cucumber, diced',
      '2 cups mixed greens',
      '2 tbsp coconut aminos',
      '1 tbsp rice vinegar (1g carb per tbsp — use sparingly)',
      '1 tsp sesame oil',
      '1 tbsp mayonnaise',
      'Sesame seeds and nori strips (optional)',
    ],
    steps: [
      'Whisk coconut aminos, vinegar, sesame oil, and mayo for dressing.',
      'Toss salmon cubes with half the dressing; rest 5 minutes.',
      'Divide greens between bowls. Top with salmon, avocado, and cucumber.',
      'Drizzle remaining dressing. Garnish with sesame and nori if using.',
    ],
    tips: 'Use previously frozen salmon for home raw preparations. Women with PCOS often do well with omega-3–rich dinners — discuss targets with your provider.',
    relatedGuideSlugs: ['pcos-and-low-carb', 'fatty-liver-low-carb', 'net-carbs-for-insulin-resistance'],
  },
  {
    slug: 'sheet-pan-chicken-thighs-cabbage',
    title: 'Sheet Pan Chicken Thighs & Cabbage',
    description:
      'One-pan OMAD-friendly dinner with crispy thighs and roasted cabbage — about 6g net carbs per serving, makes 4 portions for meal prep.',
    category: 'dinner',
    fitsPlans: ['strict_keto', 'low_carb_ir'],
    netCarbsPerServing: 6,
    proteinPerServing: 30,
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 35,
    ingredients: [
      '4 bone-in chicken thighs (skin on)',
      '1 small green cabbage, cut into wedges',
      '3 tbsp olive oil',
      '2 tsp smoked paprika',
      '1 tsp garlic powder',
      '1/2 tsp caraway seeds (optional)',
      'Salt and black pepper',
      'Lemon wedges for serving',
    ],
    steps: [
      'Preheat oven to 425°F (220°C). Line a large sheet pan.',
      'Toss cabbage wedges with 1 tbsp oil, salt, and pepper. Arrange on pan.',
      'Pat thighs dry. Rub with remaining oil, paprika, garlic powder, salt, and pepper.',
      'Nestle thighs among cabbage. Roast 32–38 minutes until skin is crisp and 165°F internal.',
      'Rest 5 minutes. Serve with lemon and pan juices.',
    ],
    tips: 'A full plate of this works as a single OMAD meal — protein, fat, and fiber in one sitting. Refrigerate leftovers up to 4 days.',
    relatedGuideSlugs: ['getting-started-keto-low-carb', 'atkins-phases-explained', 'best-first-meal-after-fasting'],
  },
];

export function getRecipeBySlug(slug: string): Recipe | undefined {
  return RECIPES.find((r) => r.slug === slug);
}

export function getRecipesByCategory(category: Recipe['category']): Recipe[] {
  return RECIPES.filter((r) => r.category === category);
}

export const RECIPE_SLUGS = RECIPES.map((r) => r.slug);

/** Curated homepage and hub cross-links — not array-order dependent */
export const FEATURED_RECIPE_SLUGS = [
  'scrambled-eggs-spinach',
  'salmon-avocado-poke-bowl',
  'sheet-pan-chicken-thighs-cabbage',
  'shakshuka-spinach-feta',
  'ginger-chicken-bone-broth-soup',
  'lettuce-wrap-burger-bowl',
] as const;

export function getFeaturedRecipes(): Recipe[] {
  return FEATURED_RECIPE_SLUGS.map((slug) => getRecipeBySlug(slug)).filter(
    (r): r is Recipe => r != null
  );
}
